--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/amos-wallpapers/wallhaven-72j8jo.jpg"

-- Special
background="#010217"
foreground="#cbd5e4"
cursor="#cbd5e4"

-- Colors
color0="#010217"
color1="#A02B67"
color2="#1E6695"
color3="#4B4EA1"
color4="#AE47A4"
color5="#3C93C2"
color6="#58A1D8"
color7="#cbd5e4"
color8="#8e959f"
color9="#A02B67"
color10="#1E6695"
color11="#4B4EA1"
color12="#AE47A4"
color13="#3C93C2"
color14="#58A1D8"
color15="#cbd5e4"
