--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/fairyos-wallpapers/wallhaven-k78j37_1920x1080.jpg"

-- Special
background="#271825"
foreground="#b8b4bc"
cursor="#b8b4bc"

-- Colors
color0="#271825"
color1="#8E6E73"
color2="#A76965"
color3="#D9735C"
color4="#D48E55"
color5="#EE8C6F"
color6="#64748C"
color7="#b8b4bc"
color8="#807d83"
color9="#8E6E73"
color10="#A76965"
color11="#D9735C"
color12="#D48E55"
color13="#EE8C6F"
color14="#64748C"
color15="#b8b4bc"
