foreground   #f1d1d7
background   #04062F
cursor       #f1d1d7

color0       #04062F
color8       #a89296
color1       #853D6F
color9       #853D6F
color2       #9A4878
color10      #9A4878
color3       #C6977D
color11      #C6977D
color4       #AF5887
color12      #AF5887
color5       #D16591
color13      #D16591
color6       #F09DB0
color14      #F09DB0
color7       #f1d1d7
color15      #f1d1d7
