# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/amos-wallpapers/wallhaven-72j8jo.jpg'

# Special
background='#010217'
foreground='#cbd5e4'
cursor='#cbd5e4'

# Colors
color0='#010217'
color1='#A02B67'
color2='#1E6695'
color3='#4B4EA1'
color4='#AE47A4'
color5='#3C93C2'
color6='#58A1D8'
color7='#cbd5e4'
color8='#8e959f'
color9='#A02B67'
color10='#1E6695'
color11='#4B4EA1'
color12='#AE47A4'
color13='#3C93C2'
color14='#58A1D8'
color15='#cbd5e4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
