--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/endeavouros/backgrounds/eos_wallpapers_community/krimkerre_2_poly.jpg"

-- Special
background="#060017"
foreground="#a19fba"
cursor="#a19fba"

-- Colors
color0="#060017"
color1="#714576"
color2="#922D61"
color3="#91586A"
color4="#172C8B"
color5="#1C2092"
color6="#2644A2"
color7="#a19fba"
color8="#706f82"
color9="#714576"
color10="#922D61"
color11="#91586A"
color12="#172C8B"
color13="#1C2092"
color14="#2644A2"
color15="#a19fba"
