foreground   #cbd5e4
background   #010217
cursor       #cbd5e4

color0       #010217
color8       #8e959f
color1       #A02B67
color9       #A02B67
color2       #1E6695
color10      #1E6695
color3       #4B4EA1
color11      #4B4EA1
color4       #AE47A4
color12      #AE47A4
color5       #3C93C2
color13      #3C93C2
color6       #58A1D8
color14      #58A1D8
color7       #cbd5e4
color15      #cbd5e4
