# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/endeavouros/backgrounds/eos_wallpapers_community/krimkerre_2_poly.jpg'

# Special
background='#060017'
foreground='#a19fba'
cursor='#a19fba'

# Colors
color0='#060017'
color1='#714576'
color2='#922D61'
color3='#91586A'
color4='#172C8B'
color5='#1C2092'
color6='#2644A2'
color7='#a19fba'
color8='#706f82'
color9='#714576'
color10='#922D61'
color11='#91586A'
color12='#172C8B'
color13='#1C2092'
color14='#2644A2'
color15='#a19fba'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
