# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/amos-wallpapers/wallhaven-6omo76.jpg'

# Special
background='#04062F'
foreground='#f1d1d7'
cursor='#f1d1d7'

# Colors
color0='#04062F'
color1='#853D6F'
color2='#9A4878'
color3='#C6977D'
color4='#AF5887'
color5='#D16591'
color6='#F09DB0'
color7='#f1d1d7'
color8='#a89296'
color9='#853D6F'
color10='#9A4878'
color11='#C6977D'
color12='#AF5887'
color13='#D16591'
color14='#F09DB0'
color15='#f1d1d7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
